name: WorldListTrashCan
version: ${version}
main: org.worldlisttrashcan.WorldListTrashCan
author: BlueNine QQ 2831508831
api-version: '1.13'
folia-supported: true
softdepend:
  - Vault
  - PlaceholderAPI
libraries:
  - "net.kyori:adventure-api:4.21.0"
  - "net.kyori:adventure-platform-bukkit:4.4.0"
  - "net.kyori:adventure-text-minimessage:4.21.0"
  - "net.kyori:adventure-text-serializer-plain:4.21.0"
commands:
  WorldListTrashCan:
    description: WorldListTrashCan插件主指令
  WTC:
    description: WorldListTrashCan插件副指令
  wtc:
    description: WorldListTrashCan插件副指令
permissions:
  WorldListTrashCan.Main:
    default: true
    description: 玩家是否能够创建世界垃圾桶
  WorldListTrashCan.BanGui:
    description: 将不回收的物品加入，如果重复加入同一物品则是取消不回收该物品
    default: true
  WorldListTrashCan.GlobalTrashOpen:
    description: 打开公共垃圾桶
    default: true
  WorldListTrashCan.help:
    description: 帮助
    default: true
  WorldListTrashCan.GlobalBan:
    description: 公共垃圾桶黑名单gui
    default: false
  WorldListTrashCan.Look:
    description: 点击实体获取实体类型
    default: false
  WorldListTrashCan.DropMode:
    description: 打开禁止丢弃模式
    default: true
  WorldListTrashCan.PlayerTrash:
    description: 玩家打开个人垃圾桶的权限
    default: true